#!/usr/bin/env python3
"""
make_env_js.py — read .env and emit env.js for the browser.

The static site can't read .env directly. This script converts the
key/value pairs into a tiny JS file that sets window.ENV.* globals.
RemoteComputeService.js reads window.ENV.OPENROUTER_API_KEY.

Usage:
    python3 make_env_js.py
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ENV_PATH = os.path.join(HERE, ".env")
OUT_PATH = os.path.join(HERE, "env.js")


def parse_env(path):
    out = {}
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" not in line:
                continue
            k, v = line.split("=", 1)
            k = k.strip()
            v = v.strip().strip('"').strip("'")
            out[k] = v
    return out


def main():
    if not os.path.exists(ENV_PATH):
        print(f"[env] {ENV_PATH} not found — create it (see .env.example pattern)")
        sys.exit(1)
    env = parse_env(ENV_PATH)
    body = (
        "// Auto-generated by make_env_js.py — DO NOT EDIT BY HAND.\n"
        "// Regenerate with: python3 make_env_js.py\n"
        "window.ENV = " + json.dumps(env, indent=2) + ";\n"
    )
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write(body)
    keys = ", ".join(env.keys()) or "(empty)"
    print(f"[env] wrote {OUT_PATH}  keys: {keys}")


if __name__ == "__main__":
    main()
